apiVersion: batch/v1
kind: CronJob
metadata:
  name: famloom-scraper
spec:
  # This cron schedule means "Run every 15 minutes"
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid # Prevents two scrapers from running at the exact same time
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper-container
            image: famloom-dataprep:local
            # Tells K8s not to try downloading this from the internet, use the local one we loaded
            imagePullPolicy: Never 
            # Injects the database credentials we secured in Action 2
            envFrom:
            - secretRef:
                name: dataprep-secrets
          restartPolicy: OnFailure