apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: famloom-dataprep-prod
  namespace: argocd
  labels:                  # <-- Must be a child of metadata
    app.kubernetes.io/name: famloom-dataprep-prod
spec:
  project: default
  source:
    repoURL: 'git@github.com:your-github-username/famloom-dataprep.git'
    targetRevision: main
    path: k8s-manifests/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
